name: CD

on:
  push:
    branches: [ "dev" ]

jobs:
  deploy-ci:
    runs-on: ubuntu-22.04

    steps: 
    - name: Checkout
      uses: actions/checkout@v3

    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        distribution: 'corretto'
        java-version: '17'
        
    - name: Create application.yml and Frebasefile.json
      run: | 
          mkdir -p src/main/resources/firebase
          echo "${{ secrets.APPLICATION }}" > src/main/resources/application.yml

    - name: create-json
      id: create-json
      uses: jsdaniell/create-json@v1.2.2
      with:
        name: "firebasekey.json"
        json: ${{ secrets.FIREBASE_FILE }}
        dir: 'src/main/resources/firebase/'

    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
      shell: bash

    - name: Build with Gradle
      run: ./gradlew build -x test
      shell: bash

    - name: Docker build Setting
      uses: docker/setup-buildx-action@v2.9.1
      
    - name: Docker hub Login
      uses: docker/login-action@v2.2.0
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_ACCESSTOKEN }}

    - name: Docker image Build and Push
      run: |
        docker build --platform linux/amd64 -t routineade/routineade-image .
        docker push routineade/routineade-image

  deploy-cd:      
    needs: deploy-ci
    runs-on: ubuntu-22.04

    steps:    
    - name: Run Docker container
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.RELEASE_SERVER_IP }}
        username: ${{ secrets.RELEASE_SERVER_USER }}
        key: ${{ secrets.RELEASE_SERVER_KEY }}
        script: |
          cd ~
          ./deploy.sh
